version: "3"

networks: 
  todonetwork:      
    driver: bridge
    name: todo-network

services:
  db:
    container_name: todo.db
    image: postgres    
    environment:
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=Postgres@123
      - POSTGRES_DB=tododb
    ports:
      - 5432:5432
    volumes:
      - ./infra/docker/Database/:/tmp/seeds/
    networks:
      - todonetwork

  rabbitmq:
    container_name: todo.rabbitmq
    image: rabbitmq:3.10-management
    environment:
      - RABBITMQ_DEFAULT_USER=todouser
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - todonetwork  

  api:
    container_name: todo.api
    image: vitormoschetta/todo.api
    build:
      context: .
      dockerfile: infra/docker/Todo.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:6001
      - ConnectionStrings__DefaultConnection=Server=todo.db;Port=5432;Database=tododb;User Id=todouser;Password=Postgres@123;
      - QueueSettings__Host=todo.rabbitmq
      - QueueSettings__Queue=TodoQueue
    ports:
      - 6001:6001
    networks:
      - todonetwork
    depends_on:
      - db
      - rabbitmq
    # logging:
    #   driver: journald

  ui.blazor:
    container_name: todo.ui.blazor
    image: vitormoschetta/todo.ui.blazor
    build:
      context: .
      dockerfile: ./infra/docker/Todo.UI.Blazor/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:6002
      - API_URL_CONNECTION=http://todo.api:6001/api/
    ports:
      - 6002:6002
    networks:
      - todonetwork
    depends_on:
      - api  

  elasticsearch:
    container_name: todo.elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:      
      - xpack.security.enabled=false
      - discovery.type=single-node
    mem_limit: 5073741824
    networks:
      - todonetwork

  kibana:
    container_name: todo.kibana
    image: docker.elastic.co/kibana/kibana:8.5.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://todo.elasticsearch:9200
      - ELASTICSEARCH_USERNAME=todouser
      - ELASTICSEARCH_PASSWORD=changeme
    networks:
      - todonetwork
    depends_on:
      - elasticsearch